<a href="https://colab.research.google.com/github/muhammedyaseenn/DATA-SCIENCE/blob/main/DATA_SCIENCE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
u

***NUMPY [NUMERICAL PYTHON]***

 It is a python library used for working with array

 used for mathematical operation

 import - import numpy as np

In [ ]:
my_list1=[1,2,3,4]
my_list2=[2,4,6,8]
result=my_list1+my_list2
print(result)

[1, 2, 3, 4, 2, 4, 6, 8]


In [ ]:
import numpy as np
array1=np.array([1,2,3,4])
array2=np.array([2,4,6,8])
result=array1+array2
print(result)

[ 3  6  9 12]


In [ ]:
import numpy as np
array1=np.array([1,2,3,4])
print(array1[1])

2


In [ ]:
#1D array
import numpy as np
array1=np.array([1,2,3,4])
print(array1[1:3])
print(array1.ndim)

[2 3]
1


In [ ]:
#2D array
import numpy as np
array1=np.array([[1,2,3,4],
                [3,5,7,9]])
print(array1.ndim)

2


In [ ]:
#3D array

import numpy as np
array1=np.array([[[1,2,3,4],
                [3,5,7,9],
                 [2,1,3,4]]])
print(array1.ndim)


3


In [ ]:
import numpy as np
array1=np.array([[[1,2,3,4],
                [10,20,30,40]],

                [[100,200,300,400],
                [1000,2000,3000,4000]]])
print(array1.ndim)
print(array1[1,1,3])

3
4000


In [ ]:
#conversion of 1D array to 2D array
import numpy as np
array1=np.array([1,2,3,4,5,6,7,8])
array2=array1.reshape(2,4)
print(array1)
print(array2)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#zeros()
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
#ones()
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [ ]:
# arange()
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#linspace
a=np.linspace(0,10)
print(a)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [ ]:
#random
a=np.random.rand(7)
print(a)

[0.04371408 0.02907021 0.738053   0.69439245 0.34586714 0.8907609
 0.55208206]


In [ ]:
import numpy as np
array1=np.array([[[1,2,3,4],
                  [3,5,7,9],
                  [2,1,3,4]]])

print(array1[1,1,3])

IndexError: index 1 is out of bounds for axis 0 with size 1

In [ ]:
array1=np.array([1,2,3,4,5,6])
array2=array1.reshape(2,3)
print(array2)

[[1 2 3]
 [4 5 6]]


# **PANDAS(Panal data system)**


*pandas is an open source python library

*used for data cleaning,data analysis,data manupulation and data visualisation preperation

*working with tabular format data or exel sheet

# pandas data **structure**

pandas mainly has two types

1. series

2.data frames

 import pandas as pd

# ***series***

series is an one dimensional labelled array


In [ ]:
import pandas as pd
marks=pd.Series([1,2,3,4,5,6])
print(marks)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [ ]:
import pandas as pd
a=pd.Series([2,4,5,3],index=["maths","physics","biology","hindi"])
print(a)


maths      2
physics    4
biology    5
hindi      3
dtype: int64


In [ ]:
import pandas as pd
a=pd.Series(["BCA","BCOM","BSC"],index=["yaseen","anshaf","shihan"])

print(a)

yaseen     BCA
anshaf    BCOM
shihan     BSC
dtype: object


In [ ]:
import pandas as pd
a=pd.Series(["BCA","BCOM","BSC"],index=["yaseen","anshaf","shihan"])
print(a["yaseen"])

BCA


# ***Data Frame***