<a href="https://colab.research.google.com/github/muhammedyaseenn/DATA-SCIENCE/blob/main/numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
marks=np.array([78,92,65,88,45,90,72,55])
print(marks)
x=np.sum(marks)
print(x)
a=np.average(marks)
print(a)
minimum=np.min(marks)
print(minimum)
maximum=np.max(marks)
print(maximum)

[78 92 65 88 45 90 72 55]
585
73.125
45
92


In [ ]:
import numpy as np
marks=np.array([78,92,65,88,45,90,72,55])
print(marks[marks>=75])
print(marks[marks<=50])





[78 92 88 90]
[45]


In [ ]:
import numpy as np
marks=np.array([78,92,65,88,45,90,72,55])
print(marks)
sort=np.sort(marks)
print(sort)


[78 92 65 88 45 90 72 55]
[45 55 65 72 78 88 90 92]


In [ ]:
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
a=np.zeros(5)
print(a)
b=np.ones(4)
print(b)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]


In [ ]:
a=np.random.randint(1,100,10)
print(a)
x=np.shape(a)
print(x)

[37 78 58 38 66 49 63 19 35 56]
(10,)


In [ ]:
temp=np.array([32,35,40,28,42,33])
x=np.mean(temp)
print(x)

35.0


In [ ]:
temp=np.array([32,35,40,28,42,33])
x=np.min(temp)
print(x)
a=np.max(temp)
print(a)

28
42


In [ ]:
temp=np.array([32,35,40,28,42,33])
temp[temp>38]=38
print(temp)

[32 35 38 28 38 33]


In [ ]:
temp=np.array([32,35,40,28,42,33])
temp2=temp.reshape(2,3)
print(temp2)


[[32 35 40]
 [28 42 33]]


In [ ]:
temp=np.array([32,35,40,28,42,33])
temp2=temp.reshape(2,3)
print(temp2[0])
print(temp2[0,1])
print(temp2[1,1])

[32 35 40]
35
42


In [ ]:
a=np.array([10,20,30,40,50,60,70,80])
print(a[0],a[7])

10 80


In [ ]:
a=np.array([10,20,30,40,50,60,70,80])
print(a[1:7])
print(a[::2])
print(a[1:7:2])

[20 30 40 50 60 70]
[10 30 50 70]
[20 40 60]


In [ ]:
a=np.array([10,20,30,40,50,60,70,80])
print(np.where(a%2==0))
print(np.where(a%2!=0))

(array([], dtype=int64),)
(array([0, 1, 2, 3, 4, 5, 6, 7]),)


In [ ]:
import pandas as pd
data=[20,30,40,90]
s=pd.Series(data)
print(s)

0    20
1    30
2    40
3    90
dtype: int64


In [ ]:
import pandas as pd
data=[20,30,40,90]
s=pd.Series(data,index=['A','B','C','D'])
print(s)

A    20
B    30
C    40
D    90
dtype: int64


In [ ]:
data={"name":"alice","age":26,"country":"japan"}
s=pd.Series(data)
print(s)

name       alice
age           26
country    japan
dtype: object


In [ ]:
data=[23,40,54,32,12,34,45]
s=pd.Series(data)
print(s.loc[2])
print(s.iloc[4])

54
12
