<a href="https://colab.research.google.com/github/muhammedyaseenn/DATA-SCIENCE/blob/main/numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NUMPY***

In [ ]:
import numpy as np
marks=np.array([78,92,65,88,45,90,72,55])
print(marks)
x=np.sum(marks)
print(x)
a=np.average(marks)
print(a)
minimum=np.min(marks)
print(minimum)
maximum=np.max(marks)
print(maximum)

[78 92 65 88 45 90 72 55]
585
73.125
45
92


In [ ]:
import numpy as np
marks=np.array([78,92,65,88,45,90,72,55])
print(marks[marks>=75])
print(marks[marks<=50])





[78 92 88 90]
[45]


In [ ]:
import numpy as np
marks=np.array([78,92,65,88,45,90,72,55])
print(marks)
sort=np.sort(marks)
print(sort)


[78 92 65 88 45 90 72 55]
[45 55 65 72 78 88 90 92]


In [ ]:
a=np.arange(1,21)
print(a)








[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
a=np.zeros(5)
print(a)
b=np.ones(4)
print(b)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]


In [ ]:
a=np.random.randint(1,100,10)
print(a)
x=np.shape(a)
print(x)

[37 78 58 38 66 49 63 19 35 56]
(10,)


In [ ]:
temp=np.array([32,35,40,28,42,33])
x=np.mean(temp)
print(x)

35.0


In [ ]:
temp=np.array([32,35,40,28,42,33])
x=np.min(temp)
print(x)
a=np.max(temp)
print(a)

28
42


In [ ]:
temp=np.array([32,35,40,28,42,33])
temp[temp>38]=38
print(temp)

[32 35 38 28 38 33]


In [ ]:
temp=np.array([32,35,40,28,42,33])
temp2=temp.reshape(2,3)
print(temp2)


[[32 35 40]
 [28 42 33]]


In [ ]:
temp=np.array([32,35,40,28,42,33])
temp2=temp.reshape(2,3)
print(temp2[0])
print(temp2[0,1])
print(temp2[1,1])

[32 35 40]
35
42


In [ ]:
a=np.array([10,20,30,40,50,60,70,80])
print(a[0],a[7])

10 80


In [ ]:
a=np.array([10,20,30,40,50,60,70,80])
print(a[1:7])
print(a[::2])
print(a[1:7:2])

[20 30 40 50 60 70]
[10 30 50 70]
[20 40 60]


In [ ]:
a=np.array([10,20,30,40,50,60,70,80])
print(np.where(a%2==0))
print(np.where(a%2!=0))

(array([], dtype=int64),)
(array([0, 1, 2, 3, 4, 5, 6, 7]),)


# ***pandas***

In [ ]:
import pandas as pd
data=[20,30,40,90]
s=pd.Series(data)
print(s)

0    20
1    30
2    40
3    90
dtype: int64


In [ ]:
import pandas as pd
data=[20,30,40,90]
s=pd.Series(data,index=['A','B','C','D'])
print(s)

A    20
B    30
C    40
D    90
dtype: int64


In [ ]:
data={"name":"alice","age":26,"country":"japan"}
s=pd.Series(data)
print(s)

name       alice
age           26
country    japan
dtype: object


In [ ]:
data=[23,40,54,32,12,34,45]
s=pd.Series(data)
print(s.loc[2])
print(s.iloc[4])

54
12


In [ ]:
DATA=[10,20,30,40]
s=pd.Series(DATA,index=["A","B","C","D"])
print(s.loc["A":"B"])
print(s.iloc[:3])

A    10
B    20
dtype: int64
A    10
B    20
C    30
dtype: int64


In [ ]:
DATA=[10,20,30,40]
s=pd.Series(DATA,index=["A","B","C","D"])
a=s[s>30]
print(a)
print(s.loc["A":"B"])
print(s.iloc[:2])


D    40
dtype: int64
A    10
B    20
dtype: int64
A    10
B    20
dtype: int64


In [ ]:
DATA=[10,20,30,40]
s=pd.Series(DATA,index=["A","B","C","D"])
a=s[s>30]
b=s[s<30]
print(a)
print(b)
print(s.loc["A":"B"])
print(s.iloc[:2])

D    40
dtype: int64
A    10
B    20
dtype: int64
A    10
B    20
dtype: int64
A    10
B    20
dtype: int64


In [ ]:
import pandas as pd
data=[20,20,30,30,50,50,60,60]
ar=pd.Series(data)
print(ar)
print(ar.unique())

0    20
1    20
2    30
3    30
4    50
5    50
6    60
7    60
dtype: int64
[20 30 50 60]


In [ ]:
import pandas as pd
data=[20,20,30,30,50,50,60,60]
ar=pd.Series(data)
print(ar)
print(ar.unique())
print(ar.nunique)

0    20
1    20
2    30
3    30
4    50
5    50
6    60
7    60
dtype: int64
[20 30 50 60]
<bound method IndexOpsMixin.nunique of 0    20
1    20
2    30
3    30
4    50
5    50
6    60
7    60
dtype: int64>


In [ ]:
data=[20,30,None,None,60,60,80]
ar=pd.Series(data)
print(ar)
print(ar.isnull())

print(ar.notnull())

0    20.0
1    30.0
2     NaN
3     NaN
4    60.0
5    60.0
6    80.0
dtype: float64
0    False
1    False
2     True
3     True
4    False
5    False
6    False
dtype: bool
0     True
1     True
2    False
3    False
4     True
5     True
6     True
dtype: bool


In [12]:
#using DATAFRAME
import pandas as pd
import numpy as np
data={
    "Name":["Alice","Bob","charlie","David","Emma"],
    "Age":[20,22,19,22,20],
    "Marks":[85,72,np.nan,90,65],
    "attendance":[95,88,75,np.nan,88],
    "city":["Kochi","Delhi","Mumbai","Kochi","chennai"]
     }
df=pd.DataFrame(data)
print("orginal DataFrame:")
print(df)

orginal DataFrame:
      Name  Age  Marks  attendance     city
0    Alice   20   85.0        95.0    Kochi
1      Bob   22   72.0        88.0    Delhi
2  charlie   19    NaN        75.0   Mumbai
3    David   22   90.0         NaN    Kochi
4     Emma   20   65.0        88.0  chennai


In [33]:
import pandas as pd
import numpy as np
data={
    "Name":["Alice","Bob","charlie","David","Emma"],
    "Age":[20,22,19,22,20],
    "Marks":[85,72,np.nan,90,65],
    "attendance":[95,88,75,np.nan,88],
    "city":["Kochi","Delhi","Mumbai","Kochi","chennai"]
     }
df=pd.DataFrame(data)
print("orginal DataFrame:")
print(df)

print("\nfirst 3 rows")
print(df.head(3))

print("\nLast 2 rows:")
print(df.tail(2))

print("\nDataFrame shape:")
print(df.shape)

print("\nDataFrame columns:")
print(df.columns)

print("\nMarks column:")
print(df["Marks"])

print("\nfirst 3 rows:")
print(df.iloc[0:3])

print("\nrows 1 to 3,Name and Marks:")
print(df.loc[1:3,["Name","Marks"]])

print("\nstudents with marks greater than 75:")
print(df[df["Marks"]>75])

print("\nstudents from kochi:")
print(df[df["city"]=="Kochi"])

print("\nstudents with marks > 70 and attendance > 80:")
print(df[
         (df["Marks"]>70) &
         (df["attendance"]>80)
]
)

orginal DataFrame:
      Name  Age  Marks  attendance     city
0    Alice   20   85.0        95.0    Kochi
1      Bob   22   72.0        88.0    Delhi
2  charlie   19    NaN        75.0   Mumbai
3    David   22   90.0         NaN    Kochi
4     Emma   20   65.0        88.0  chennai

first 3 rows
      Name  Age  Marks  attendance    city
0    Alice   20   85.0        95.0   Kochi
1      Bob   22   72.0        88.0   Delhi
2  charlie   19    NaN        75.0  Mumbai

Last 2 rows:
    Name  Age  Marks  attendance     city
3  David   22   90.0         NaN    Kochi
4   Emma   20   65.0        88.0  chennai

DataFrame shape:
(5, 5)

DataFrame columns:
Index(['Name', 'Age', 'Marks', 'attendance', 'city'], dtype='object')

Marks column:
0    85.0
1    72.0
2     NaN
3    90.0
4    65.0
Name: Marks, dtype: float64

first 3 rows:
      Name  Age  Marks  attendance    city
0    Alice   20   85.0        95.0   Kochi
1      Bob   22   72.0        88.0   Delhi
2  charlie   19    NaN        75.0  Mum

In [38]:
#mathematical operations
import pandas as pd
import numpy as np
data={
    "Name":["Alice","Bob","charlie","David","Emma"],
    "Age":[20,22,19,22,20],
    "Marks":[85,72,np.nan,90,65],
    "attendance":[95,88,75,np.nan,88],
    "city":["Kochi","Delhi","Mumbai","Kochi","chennai"]
     }
df=pd.DataFrame(data)
print("orginal DataFrame:")
print(df)

print("\nMarks + 5:")
print(df["Marks"]+5)

print("\nMarks * 2:")
print(df["Marks"]*2)

print("\nAverage Marks:")
print(df["Marks"].mean())

print("\nMaximum Mark:")
print(df["Marks"].max())

print("\nMinimum Mark:")
print(df["Marks"].min())

orginal DataFrame:
      Name  Age  Marks  attendance     city
0    Alice   20   85.0        95.0    Kochi
1      Bob   22   72.0        88.0    Delhi
2  charlie   19    NaN        75.0   Mumbai
3    David   22   90.0         NaN    Kochi
4     Emma   20   65.0        88.0  chennai

Marks + 5:
0    90.0
1    77.0
2     NaN
3    95.0
4    70.0
Name: Marks, dtype: float64

Marks * 2:
0    170.0
1    144.0
2      NaN
3    180.0
4    130.0
Name: Marks, dtype: float64

Average Marks:
78.0

Maximum Mark:
90.0

Minimum Mark:
65.0


In [42]:
#sorting
import pandas as pd
import numpy as np
data={
    "Name":["Alice","Bob","charlie","David","Emma"],
    "Age":[20,22,19,22,20],
    "Marks":[85,72,np.nan,90,65],
    "attendance":[95,88,75,np.nan,88],
    "city":["Kochi","Delhi","Mumbai","Kochi","chennai"]
     }
df=pd.DataFrame(data)
print("orginal DataFrame:")
print(df)

print("\nSorting by Marks:")
print(df.sort_values("Marks"))

print("\nSorted by Marks - Highest first:")
print(df.sort_values("Marks",ascending=False))


orginal DataFrame:
      Name  Age  Marks  attendance     city
0    Alice   20   85.0        95.0    Kochi
1      Bob   22   72.0        88.0    Delhi
2  charlie   19    NaN        75.0   Mumbai
3    David   22   90.0         NaN    Kochi
4     Emma   20   65.0        88.0  chennai

Sorting by Marks:
      Name  Age  Marks  attendance     city
4     Emma   20   65.0        88.0  chennai
1      Bob   22   72.0        88.0    Delhi
0    Alice   20   85.0        95.0    Kochi
3    David   22   90.0         NaN    Kochi
2  charlie   19    NaN        75.0   Mumbai

Sorted by Marks - Highest first:
      Name  Age  Marks  attendance     city
3    David   22   90.0         NaN    Kochi
0    Alice   20   85.0        95.0    Kochi
1      Bob   22   72.0        88.0    Delhi
4     Emma   20   65.0        88.0  chennai
2  charlie   19    NaN        75.0   Mumbai


In [44]:
#renaming columns
import pandas as pd
import numpy as np
data={
    "Name":["Alice","Bob","charlie","David","Emma"],
    "Age":[20,22,19,22,20],
    "Marks":[85,72,np.nan,90,65],
    "attendance":[95,88,75,np.nan,88],
    "city":["Kochi","Delhi","Mumbai","Kochi","chennai"]
     }
df=pd.DataFrame(data)
print("orginal DataFrame:")
print(df)

df_renamed=df.rename(
    columns={
        "Marks":"Score",
        "Attendance":"Attendance_percentage"
    }
)

print("\nRenamed DataFrame:")
print(df_renamed)

orginal DataFrame:
      Name  Age  Marks  attendance     city
0    Alice   20   85.0        95.0    Kochi
1      Bob   22   72.0        88.0    Delhi
2  charlie   19    NaN        75.0   Mumbai
3    David   22   90.0         NaN    Kochi
4     Emma   20   65.0        88.0  chennai

Renamed DataFrame:
      Name  Age  Score  attendance     city
0    Alice   20   85.0        95.0    Kochi
1      Bob   22   72.0        88.0    Delhi
2  charlie   19    NaN        75.0   Mumbai
3    David   22   90.0         NaN    Kochi
4     Emma   20   65.0        88.0  chennai


In [45]:
#checking missing values
import pandas as pd
import numpy as np
data={
    "Name":["Alice","Bob","charlie","David","Emma"],
    "Age":[20,22,19,22,20],
    "Marks":[85,72,np.nan,90,65],
    "attendance":[95,88,75,np.nan,88],
    "city":["Kochi","Delhi","Mumbai","Kochi","chennai"]
     }
df=pd.DataFrame(data)
print("orginal DataFrame:")
print(df)

print("\nMissing values:")
print(df.isna())

print("\nNumber of missing values")
print(df.isna().sum())

orginal DataFrame:
      Name  Age  Marks  attendance     city
0    Alice   20   85.0        95.0    Kochi
1      Bob   22   72.0        88.0    Delhi
2  charlie   19    NaN        75.0   Mumbai
3    David   22   90.0         NaN    Kochi
4     Emma   20   65.0        88.0  chennai

Missing values:
    Name    Age  Marks  attendance   city
0  False  False  False       False  False
1  False  False  False       False  False
2  False  False   True       False  False
3  False  False  False        True  False
4  False  False  False       False  False

Number of missing values
Name          0
Age           0
Marks         1
attendance    1
city          0
dtype: int64


In [46]:
#forward fill and backward fill
import pandas as pd
import numpy as np
data={
    "Name":["Alice","Bob","charlie","David","Emma"],
    "Age":[20,22,19,22,20],
    "Marks":[85,72,np.nan,90,65],
    "attendance":[95,88,75,np.nan,88],
    "city":["Kochi","Delhi","Mumbai","Kochi","chennai"]
     }
df=pd.DataFrame(data)
print("orginal DataFrame:")
print(df)

df_forward=df.copy()

df_forward=df_forward.ffill()

print("\nforward fill:")
print(df_forward)

orginal DataFrame:
      Name  Age  Marks  attendance     city
0    Alice   20   85.0        95.0    Kochi
1      Bob   22   72.0        88.0    Delhi
2  charlie   19    NaN        75.0   Mumbai
3    David   22   90.0         NaN    Kochi
4     Emma   20   65.0        88.0  chennai

forward fill:
      Name  Age  Marks  attendance     city
0    Alice   20   85.0        95.0    Kochi
1      Bob   22   72.0        88.0    Delhi
2  charlie   19   72.0        75.0   Mumbai
3    David   22   90.0        75.0    Kochi
4     Emma   20   65.0        88.0  chennai
